download_url: https://galaxy.ansible.com/download/junipernetworks-junos-4.1.0.tar.gz
format_version: 1.0.0
name: junos
namespace: junipernetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.1.0
version_url: https://galaxy.ansible.com/api/v2/collections/junipernetworks/junos/versions/4.1.0/
