---
- name: Collect CPU Load Details
  cisco.ios.ios_command:
    commands:
      - show processes cpu history
  register: cpu

- name: Task 2 - Parse CPU Data from 'cpu'
  set_fact:
    cpu_history: "{{ cpu.stdout[0] | clay584.genie.parse_genie(command='show processes cpu history', os='ios') }}"


# - name: Display 'cpu_data' data
#   debug:
#     msg: 
#       - "Average CPU Load in 60sec: {{ cpu_history | cpu60sec }}%"
#       - "Average CPU Load in 60min: {{ cpu_history | cpu60min }}%"
#       - "Average CPU Load in 72hrs: {{ cpu_history | cpu72hrs }}%"