---
- name: Collect CPU Load Details
  cisco.ios.ios_command:
    commands:
      - show processes cpu sorted
  register: cpu_sorted

- name: Task 2 - Parse CPU Data from 'cpu'
  set_fact:
    cpu_sorted: "{{ cpu_sorted.stdout[0] | clay584.genie.parse_genie(command='show processes cpu sorted', os='ios') }}"

- name: Save 'cpu_sorted' to a file
  copy:
    content: "{{ cpu_sorted | to_nice_json }}"
    dest: cpu_sorted.json


# - name: Display 'cpu_data' data
#   debug:
#     msg: 
#       - "Average CPU Load in 60sec: {{ cpu_history | cpu60sec }}%"
#       - "Average CPU Load in 60min: {{ cpu_history | cpu60min }}%"
#       - "Average CPU Load in 72hrs: {{ cpu_history | cpu72hrs }}%"