---
- name: Collect Uptime Details
  cisco.ios.ios_command:
    commands:
      - sho version
  register: uptime

- name: Task 2 - Parse uptime Data from 'uptime'
  set_fact:
    uptime_data: "{{ uptime.stdout[0] | clay584.genie.parse_genie(command='show version', os='ios') }}"

# - name: Display 'uptime_data' data
#   debug:
#     msg: 
#       - "Device Uptime: {{ uptime_data['version']['uptime'] }}"
#       - "Last Rebooted: {{ uptime_data['version']['system_restarted_at'] }}"
#       - "Reboot Reason: {{ uptime_data['version']['last_reload_reason'] }}"
